baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Termeul'
theme = 'termeul'
disableKinds = ["taxonomy", "term"]

[[menus.main]]
name = 'Posts'
pageRef = 'posts'
weight = 10

[markup.goldmark.renderer]
unsafe = true