name: Publish to GitHub pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.139.4
      HUGO_TZ: Europe/Berlin
    steps:
      - name: Install Hugo
        shell: bash
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build with Hugo
        working-directory: ./exampleSite
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: ${{ env.HUGO_TZ }}
        run: |
          hugo --gc --minify --themesDir="../.." --baseURL "https://joogswastaken.github.io/termeul" -t termeul
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: exampleSite/public
